[package]
name = "titan-ring"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "ring"
harness = false
