[package]
name = "titan-net"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
titan-ring = { workspace = true }
titan-proto = { workspace = true }
mio = { workspace = true }
socket2 = { workspace = true }
